# CONFIGURACION CONTEXTO
server:
  port: 9101

spring:
  # MONGODB
  data:
    mongodb:
      uri: mongodb+srv://mongoAtlas:m0ngo4tlas@cluster0.siwst.mongodb.net/walletHolder?retryWrites=true&w=majority
  # KAFKA
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: walletholder1
      topic.name: "WALLET-ACCOUNT-CREATED"
    properties:
      spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#===========================================================================
# CONFIG SERVER
#===========================================================================
#
spring.cloud.discovery.enabled: false
spring.cloud.config.discovery.enabled: false
spring.cloud.config.enabled: false

#===========================================================================
# LOGS
#===========================================================================
log:
  path: /opt/logs/ms-wallet-holder
logging:
  level:
    org.mongodb.driver: ERROR
